import os
from arcadepy import Arcade
from supabase import create_client

# 1. Initialize the Arcade Client
client = Arcade(api_key=os.environ.get("ARCADE_API_KEY"))

# 2. Initialize Supabase
supabase_url = os.environ.get("SUPABASE_URL")
supabase_key = os.environ.get("SUPABASE_KEY")
supabase = create_client(supabase_url, supabase_key)

def get_market_data(ticker: str):
    """
    Fetches live price using the exact parameters seen in Arcade dashboard:
    tool: GoogleFinance.GetStockSummary
    params: ticker_symbol, exchange_identifier
    """
    # Splitting TICKER.NS (Yahoo style) to SULA and NSE (Arcade style)
    if '.' in ticker:
        symbol, suffix = ticker.split('.')
        exchange = "NSE" if suffix.upper() in ["NS", "NSE"] else "BSE"
    else:
        symbol, exchange = ticker, "NSE"

    return client.tools.execute(
        tool_name="GoogleFinance.GetStockSummary",
        input={
            "ticker_symbol": symbol,
            "exchange_identifier": exchange
        }
    )

def send_investor_briefing(recipient: str, ticker: str, analysis: str):
    """Executive: Sends the briefing using the verified Gmail namespace."""
    return client.tools.execute(
        # Matches Arcade dashboard: Gmail.SendEmail
        tool_name="Gmail.SendEmail", 
        input={
            "recipient": "amar.v@outlook.com",
            "subject": f"Artha Execution Brief: {ticker}",
            "body": f"Strategic analysis for {ticker}:\n\n{analysis}"
        },
        user_id="amarprasad.v@gmail.com" 
    )

def schedule_trade_review(ticker: str):
    """Executive: Calendar Tool."""
    try:
        return client.tools.execute(
            tool_name="GoogleCalendar.CreateEvent", 
            input={
                "summary": f"Review {ticker} Trade Execution",
                "description": "Automated trade review generated by Artha-Agent.",
                "start_datetime": f"Tomorrow 10am",
                "end_datetime": f"Tomorrow 10am"
            },
            user_id="amarprasad.v@gmail.com"
        )
    except Exception as e:
        print(f"Calendar Action Skipped: {e}")
        return {"status": "skipped", "reason": "auth_required"}

def archive_research_note(content: str):
    """Information: Saves persistent data to Supabase."""
    try:
        return supabase.table("notes").insert({
            "content": content
        }).execute()
    except Exception as e:
        print(f"Archive Action Skipped: {e}")
        return {"status": "skipped", "reason": "Error"}

def get_personal_strategy(ticker: str):
    """Retrieves target from Supabase."""
    response = supabase.table("watchlist").select("*").eq("ticker", ticker).execute()
    return response.data[0] if response.data else {}